version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: notvolt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: notvolt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: notvolt-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3
    container_name: notvolt-lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx512m
      - SERVER_PORT=${LAVALINK_PORT:-2333}
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD:-youshallnotpass}
    ports:
      - "2333:2333"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro

volumes:
  postgres-data:
  redis-data:
