server:
  port: 8080

spring:
  application:
    name: notvolt-web
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/notvolt}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id
        registration:
          discord:
            client-id: ${NOTVOLT_CLIENT_ID:}
            client-secret: ${NOTVOLT_CLIENT_SECRET:}
            client-name: Discord
            scope: ["identify", "email"]
            provider: discord
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    tags:
      application: notvolt-web
